### ISSUE TITLE
Include more Deeptools tool

### ISSUE THREAD

**Issue by JihedC** [JihedC/Snakemake_ATAC_2020#1]
For the pipeline we also want to include the following tools: 

- [bamPEFragmentSize](https://deeptools.readthedocs.io/en/develop/content/tools/bamPEFragmentSize.html)
- [plotCorrelation](https://deeptools.readthedocs.io/en/develop/content/tools/plotCorrelation.html)
- [plotProfile](https://deeptools.readthedocs.io/en/develop/content/tools/plotProfile.html)

**Comment by WJH58** [comment]
@JihedC These three deeptools have been added to the pipeline on dev branch.

**Comment by JihedC** [comment]
Does it work? Can you show the output?

**Comment by WJH58** [comment]
@JihedC They all work. I tested the pipeline with morc3 real data, here attached all of the outputs of deeptools: 
1. rule plotCorrelation
[correlation.pdf](https://github.com/JihedC/Snakemake_ATAC_2020/files/5991053/correlation.pdf) 
2. rule bamPEFragmentSize:
[histogram.pdf](https://github.com/JihedC/Snakemake_ATAC_2020/files/5991080/histogram.pdf)
3. rule plotHeatmap
[heatmap_reference_point_genes.pdf](https://github.com/JihedC/Snakemake_ATAC_2020/files/5991082/heatmap_reference_point_genes.pdf)
4. rule plotProfile
[profile_reference_point_genes.pdf](https://github.com/JihedC/Snakemake_ATAC_2020/files/5991086/profile_reference_point_genes.pdf)
5. rule PCA
[PCA_PLOT.pdf](https://github.com/JihedC/Snakemake_ATAC_2020/files/5991087/PCA_PLOT.pdf)

**Comment by JihedC** [comment]
Can you please show me the result you got for H3.3 and Morc3 ATAC analysis?

**Comment by WJH58** [comment]
@JihedC 
H3.3:
[correlation.pdf](https://github.com/JihedC/Snakemake_ATAC_2020/files/6241779/correlation.pdf)
[profile_reference_point_genes.pdf](https://github.com/JihedC/Snakemake_ATAC_2020/files/6241831/profile_reference_point_genes.pdf)
[histogram.pdf](https://github.com/JihedC/Snakemake_ATAC_2020/files/6241840/histogram.pdf)
[PCA_PLOT.pdf](https://github.com/JihedC/Snakemake_ATAC_2020/files/6241799/PCA_PLOT.pdf)

Morc3:
[correlation_bs50.pdf](https://github.com/JihedC/Snakemake_ATAC_2020/files/6241805/correlation_bs50.pdf)
[histogram.pdf](https://github.com/JihedC/Snakemake_ATAC_2020/files/6241810/histogram.pdf)
[profile_reference_point_genes.pdf](https://github.com/JihedC/Snakemake_ATAC_2020/files/6241813/profile_reference_point_genes.pdf)
[PCA_PLOT_bs50.pdf](https://github.com/JihedC/Snakemake_ATAC_2020/files/6241816/PCA_PLOT_bs50.pdf)
