### ISSUE TITLE
HMMRATAC_V1.2.10_exe.jar is not downloaded before runnning hmmratac rule

### ISSUE THREAD

**Issue by WJH58** [JihedC/Snakemake_ATAC_2020#12]
Snakemake conducts the rules in a random order. Sometimes HMMRATAC_V1.2.10_exe.jar isn't downloaded before rule hmmratac starts, which results in failure of rule hmmratac.

**Comment by WJH58** [comment]
@JihedC Conda installation worked if we add "-Xxm48G" after "HMMRATAC" command. Therefore we don't need this download_hmmratac rule anymore.

**Comment by JihedC** [comment]
Do you mean that you use a conda environment for the rule HMMRATAC?

**Comment by WJH58** [comment]
yes

**Comment by JihedC** [comment]
Ok that's good then I close this issue
