### ISSUE TITLE
Change name of launcher

### ISSUE THREAD

**Issue by JihedC** [JihedC/Snakemake_ATAC_2020#14]
Hi Jianhui,

for now the script that initiate the pipeline on slurm is `slurm_minisnakemake.sh`, could you change its name? 
Because it's not a minisnakemake anymore. 
Don't forget to modify your readme file accordingly.

**Comment by WJH58** [comment]
@JihedC "slurm_minisnakemake.sh" has been changed to "slurm_snakemake.sh". File names in README have been altered correspondingly as well. Dag photo was updated because we deleted rule download_hmmratac.
