### ISSUE TITLE
Add MultiQC 

### ISSUE THREAD

**Issue by JihedC** [JihedC/Snakemake_ATAC_2020#5]
https://github.com/ewels/MultiQC

**Comment by WJH58** [comment]
@JihedC I have added rule multiQC. It produced a QC summary across all samples **after trimming** and stored the results in results/trimmed_fastqc.

**Comment by WJH58** [comment]
@JihedC I changed the command line to ```multiqc . 2>{log}```. So it searched the whole ATAC-seq_pipeline and produced the results in this folder. 
this is the screenshot of html report:
<img width="1437" alt="Screenshot 2021-02-24 at 16 00 35" src="https://user-images.githubusercontent.com/73345650/109019662-7b9f5900-76b9-11eb-9f6c-2753dfd0497b.png">

**Comment by JihedC** [comment]
Can you upload the multiQC html reports and the folder associated with it on Idrive?

**Comment by WJH58** [comment]
@JihedC I added them in /Jianhui/Morc3_ATAC/output/multiQC
