### ISSUE TITLE
Add annotation of the peaks with Homer 

### ISSUE THREAD

**Issue by JihedC** [JihedC/Snakemake_ATAC_2020#6]
Homer can be used to annotate the peaks detected by ATAC-seq. This will give us information about the genomic feature associated with the peak.

Information about peak annotation: http://homer.ucsd.edu/homer/ngs/annotation.html

Homer can be installed with Conda:  https://anaconda.org/bioconda/homer

**Comment by WJH58** [comment]
@JihedC Rule homer has been added to the pipeline on dev branch.

**Comment by JihedC** [comment]
Ok! 
Can you provide an example of the output?

**Comment by WJH58** [comment]
@JihedC The outputs of homer are stored in: /exports/humgen/Jianhui/pipeline_test/Snakemake_ATAC_2020/ATAC-seq_pipeline/results/annotation. There are KO1_annotate_homer.txt, KO2_annotate_homer.txt, WT1_annotate_homer.txt, WT2_annotate_homer.txt.

Here attached one example: KO1_annotate_homer.txt
<img width="1440" alt="Screenshot 2021-02-17 at 09 12 05" src="https://user-images.githubusercontent.com/73345650/108174803-3a7ad800-7100-11eb-939f-28a018070f9a.png">

**Comment by JihedC** [comment]
I am not sure it work, there are no annotation of your peaks

**Comment by JihedC** [comment]
If it still does not work may be you can just give instructions to the user on how to perform the annotation.

**Comment by WJH58** [comment]
@JihedC I've tried my best but I can't make Snakemake install mm10 when running the pipeline. Can we delete this rule? How do I give instruction? Can I state it in README?

**Comment by WJH58** [comment]
@JihedC Maybe do you know someone who is good at Perl?

**Comment by WJH58** [comment]
@JihedC I added a "Annotate peaks using Homer.md" file on dev branch.

**Comment by JihedC** [comment]
perfect!
