### ISSUE TITLE
HMMRATAC is not downloaded by the pipeline

### ISSUE THREAD

**Issue by JihedC** [JihedC/Snakemake_ATAC_2020#8]
Now HMMRATAC works but the tool is not downloaded by the pipeline. 
We can either add a rule to download it from GitHub (also include a touch command) or try to use the conda version of HMMRATAC.

First try conda, it's the simplest.

**Comment by WJH58** [comment]
@JihedC I used "touch" in the output, see below:
```    
  rule download_hmmratac:
    output:
        touch(WORKING_DIR + "hmmratac.java")
    params:
        hmmratac = config["HMMRATAC"]
    log:
        RESULT_DIR + "logs/hmmratac/download_hmmratac_github.log"
    shell:
        "wget {params.hmmratac}"
```
We're going to download HMMRATAC_V1.2.10_exe.jar rather than via conda installation. This rule downloads hmmratac, but the problem becomes how to make it work before rule hmmratac works.
